import type { AppRole } from "../src/lib/auth/roles";

export type FixtureProfile =
  | "platform_core"
  | "master_data"
  | "procurement_core"
  | "society_security"
  | "hrms_core"
  | "service_ops"
  | "workflow";

export type FeatureModuleGroup =
  | "platform_master"
  | "procurement_billing"
  | "society_security"
  | "hrms_service";

export type EntityExpectation = {
  table: string;
  minCount?: number;
};

export type ApiExpectation = {
  path: string;
  method?: "GET" | "POST";
  body?: Record<string, unknown>;
  expectedStatus?: number;
};

export type FeatureWave1Check = {
  route: string;
  readyText?: string;
  ctaText?: string;
  emptyStateText?: string;
  secondaryText?: string;
  entityChecks?: EntityExpectation[];
  apiChecks?: ApiExpectation[];
};

export type WorkflowScenarioKey =
  | "super_admin_runtime_chain"
  | "material_supply_chain"
  | "visitor_society_chain"
  | "hrms_attendance_leave_payroll_chain"
  | "ac_job_execution_chain"
  | "service_deployment_chain"
  | "pest_job_chain";

export type FeatureWorkflowScenario = {
  scenarioKey: WorkflowScenarioKey;
  title: string;
  ownerRoles: AppRole[];
  statusTransitions: string[];
  evidenceTables: string[];
};

export type ScopedFeatureTestConfig = {
  scopeSection: string;
  title: string;
  featureKey: string;
  moduleGroup: FeatureModuleGroup;
  routes: string[];
  primaryRoles: AppRole[];
  fixtureProfile: FixtureProfile;
  wave1Checks: FeatureWave1Check[];
  wave2Scenario?: FeatureWorkflowScenario;
  expectedEntities: string[];
  expectedNotifications: string[];
  deferredReason?: string;
};

function feature(config: ScopedFeatureTestConfig) {
  return config;
}

const platformMasterFeatures: ScopedFeatureTestConfig[] = [
  feature({
    scopeSection: "11.1",
    title: "Admin Management",
    featureKey: "platform-admin-management",
    moduleGroup: "platform_master",
    routes: ["/settings/admins"],
    primaryRoles: ["super_admin"],
    fixtureProfile: "platform_core",
    wave1Checks: [
      {
        route: "/settings/admins",
        readyText: "Admin Management",
        ctaText: "Invite Admin",
        entityChecks: [{ table: "users", minCount: 18 }, { table: "audit_logs", minCount: 1 }],
        apiChecks: [{ path: "/api/super-admin/admins", method: "POST", body: {}, expectedStatus: 400 }],
      },
    ],
    expectedEntities: ["users", "roles", "audit_logs"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "11.1",
    title: "Role & Permissions",
    featureKey: "platform-rbac",
    moduleGroup: "platform_master",
    routes: ["/settings/permissions"],
    primaryRoles: ["super_admin"],
    fixtureProfile: "platform_core",
    wave1Checks: [
      {
        route: "/settings/permissions",
        readyText: "Role & Permissions",
        ctaText: "Save Role Permissions",
        entityChecks: [{ table: "roles", minCount: 18 }],
      },
    ],
    expectedEntities: ["roles", "audit_logs"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "11.1",
    title: "Audit Logs",
    featureKey: "platform-audit-logs",
    moduleGroup: "platform_master",
    routes: ["/settings/audit-logs"],
    primaryRoles: ["super_admin"],
    fixtureProfile: "platform_core",
    wave1Checks: [
      {
        route: "/settings/audit-logs",
        readyText: "Audit Logs",
        entityChecks: [{ table: "audit_logs", minCount: 1 }],
      },
    ],
    expectedEntities: ["audit_logs"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "11.1",
    title: "System Configuration",
    featureKey: "platform-system-config",
    moduleGroup: "platform_master",
    routes: ["/settings/company"],
    primaryRoles: ["super_admin"],
    fixtureProfile: "platform_core",
    wave1Checks: [
      {
        route: "/settings/company",
        readyText: "System Configuration",
        ctaText: "Save System Configuration",
        entityChecks: [{ table: "system_config", minCount: 1 }],
      },
    ],
    expectedEntities: ["system_config", "audit_logs"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "7.1",
    title: "Company Users",
    featureKey: "company-users",
    moduleGroup: "platform_master",
    routes: ["/company/users"],
    primaryRoles: ["admin"],
    fixtureProfile: "master_data",
    wave1Checks: [{ route: "/company/users", entityChecks: [{ table: "users", minCount: 18 }] }],
    expectedEntities: ["users", "roles"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "7.1",
    title: "Designation Master",
    featureKey: "company-designations",
    moduleGroup: "platform_master",
    routes: ["/company/designations"],
    primaryRoles: ["admin"],
    fixtureProfile: "master_data",
    wave1Checks: [
      { route: "/company/designations", entityChecks: [{ table: "designations", minCount: 1 }] },
    ],
    expectedEntities: ["designations"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "7.1",
    title: "Employee Master",
    featureKey: "company-employees",
    moduleGroup: "platform_master",
    routes: ["/company/employees"],
    primaryRoles: ["admin"],
    fixtureProfile: "master_data",
    wave1Checks: [{ route: "/company/employees", entityChecks: [{ table: "employees", minCount: 1 }] }],
    expectedEntities: ["employees", "designations"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "7.1",
    title: "Location Master",
    featureKey: "company-locations",
    moduleGroup: "platform_master",
    routes: ["/company/locations"],
    primaryRoles: ["admin"],
    fixtureProfile: "master_data",
    wave1Checks: [
      { route: "/company/locations", entityChecks: [{ table: "company_locations", minCount: 1 }] },
    ],
    expectedEntities: ["company_locations"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "7.2",
    title: "Product Categories",
    featureKey: "inventory-categories",
    moduleGroup: "platform_master",
    routes: ["/inventory/categories"],
    primaryRoles: ["admin"],
    fixtureProfile: "master_data",
    wave1Checks: [
      { route: "/inventory/categories", entityChecks: [{ table: "product_categories", minCount: 1 }] },
    ],
    expectedEntities: ["product_categories"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "7.2",
    title: "Products",
    featureKey: "inventory-products",
    moduleGroup: "platform_master",
    routes: ["/inventory/products"],
    primaryRoles: ["admin"],
    fixtureProfile: "master_data",
    wave1Checks: [{ route: "/inventory/products", entityChecks: [{ table: "products", minCount: 1 }] }],
    expectedEntities: ["products", "product_categories", "product_subcategories"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "7.2",
    title: "Suppliers",
    featureKey: "inventory-suppliers",
    moduleGroup: "platform_master",
    routes: ["/inventory/suppliers"],
    primaryRoles: ["admin"],
    fixtureProfile: "master_data",
    wave1Checks: [{ route: "/inventory/suppliers", entityChecks: [{ table: "suppliers", minCount: 1 }] }],
    expectedEntities: ["suppliers"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "7.2",
    title: "Supplier Rates",
    featureKey: "inventory-supplier-rates",
    moduleGroup: "platform_master",
    routes: ["/inventory/supplier-rates"],
    primaryRoles: ["admin"],
    fixtureProfile: "master_data",
    wave1Checks: [
      {
        route: "/inventory/supplier-rates",
        entityChecks: [{ table: "suppliers", minCount: 1 }, { table: "products", minCount: 1 }],
      },
    ],
    expectedEntities: ["supplier_rates", "suppliers", "products"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "7.3",
    title: "Checklist Master",
    featureKey: "services-masters-checklists",
    moduleGroup: "platform_master",
    routes: ["/services/masters/checklists"],
    primaryRoles: ["admin"],
    fixtureProfile: "master_data",
    wave1Checks: [
      {
        route: "/services/masters/checklists",
        entityChecks: [{ table: "daily_checklists", minCount: 1 }],
      },
    ],
    expectedEntities: ["daily_checklists"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "7.3",
    title: "Work Master",
    featureKey: "services-masters-work",
    moduleGroup: "platform_master",
    routes: ["/services/masters/work-master"],
    primaryRoles: ["admin"],
    fixtureProfile: "master_data",
    wave1Checks: [{ route: "/services/masters/work-master" }],
    expectedEntities: ["work_master", "services_wise_work"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "7.3",
    title: "Vendor Wise Services",
    featureKey: "services-vendor-services",
    moduleGroup: "platform_master",
    routes: ["/services/masters/vendor-services"],
    primaryRoles: ["admin"],
    fixtureProfile: "master_data",
    wave1Checks: [
      {
        route: "/services/masters/vendor-services",
        entityChecks: [{ table: "vendor_wise_services", minCount: 1 }],
      },
    ],
    expectedEntities: ["vendor_wise_services", "suppliers", "services"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "9.1",
    title: "Employee Profiles",
    featureKey: "hrms-profiles",
    moduleGroup: "platform_master",
    routes: ["/hrms/profiles"],
    primaryRoles: ["admin"],
    fixtureProfile: "hrms_core",
    wave1Checks: [
      {
        route: "/hrms/profiles",
        readyText: "HRMS / Employee Profiles",
        entityChecks: [{ table: "employees", minCount: 1 }],
      },
    ],
    expectedEntities: ["employees"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "9.1",
    title: "Specialized Profiles",
    featureKey: "hrms-specialized-profiles",
    moduleGroup: "platform_master",
    routes: ["/hrms/specialized-profiles"],
    primaryRoles: ["admin"],
    fixtureProfile: "hrms_core",
    wave1Checks: [
      {
        route: "/hrms/specialized-profiles",
        readyText: "Specialized Personnel Profiles",
        emptyStateText: "No Specialized Profiles Found",
        entityChecks: [{ table: "technician_profiles", minCount: 1 }],
      },
    ],
    expectedEntities: ["technician_profiles", "employees"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "9.1",
    title: "Employee Documents",
    featureKey: "hrms-documents",
    moduleGroup: "platform_master",
    routes: ["/hrms/documents"],
    primaryRoles: ["admin"],
    fixtureProfile: "hrms_core",
    wave1Checks: [{ route: "/hrms/documents", readyText: "Document Governance", ctaText: "Upload Document" }],
    expectedEntities: ["employee_documents", "employees"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "9.1",
    title: "Shift Master",
    featureKey: "hrms-shifts",
    moduleGroup: "platform_master",
    routes: ["/hrms/shifts"],
    primaryRoles: ["admin"],
    fixtureProfile: "hrms_core",
    wave1Checks: [
      {
        route: "/hrms/shifts",
        readyText: "Shift Master",
        ctaText: "Assign Guard to Shift",
        entityChecks: [{ table: "shifts", minCount: 1 }, { table: "employee_shift_assignments", minCount: 1 }],
      },
    ],
    expectedEntities: ["shifts", "employee_shift_assignments"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "9.1",
    title: "Leave Configuration",
    featureKey: "hrms-leave-config",
    moduleGroup: "platform_master",
    routes: ["/hrms/leave/config"],
    primaryRoles: ["admin"],
    fixtureProfile: "hrms_core",
    wave1Checks: [
      {
        route: "/hrms/leave/config",
        readyText: "Leave Configuration",
        entityChecks: [{ table: "leave_types", minCount: 1 }],
      },
    ],
    expectedEntities: ["leave_types"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "9.1",
    title: "Holiday Master",
    featureKey: "hrms-holidays",
    moduleGroup: "platform_master",
    routes: ["/hrms/holidays"],
    primaryRoles: ["admin"],
    fixtureProfile: "hrms_core",
    wave1Checks: [
      {
        route: "/hrms/holidays",
        readyText: "Holiday Master",
        entityChecks: [{ table: "holidays", minCount: 1 }],
      },
    ],
    expectedEntities: ["holidays"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "9.1",
    title: "Company Events",
    featureKey: "hrms-events",
    moduleGroup: "platform_master",
    routes: ["/hrms/events"],
    primaryRoles: ["admin"],
    fixtureProfile: "hrms_core",
    wave1Checks: [
      {
        route: "/hrms/events",
        readyText: "Company Events",
        entityChecks: [{ table: "company_events", minCount: 1 }],
      },
    ],
    expectedEntities: ["company_events"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "13",
    title: "Platform API Family",
    featureKey: "platform-api-family",
    moduleGroup: "platform_master",
    routes: ["/settings/admins", "/settings/permissions", "/settings/audit-logs"],
    primaryRoles: ["super_admin"],
    fixtureProfile: "platform_core",
    wave1Checks: [
      {
        route: "/settings/admins",
        readyText: "Admin Management",
        apiChecks: [{ path: "/api/super-admin/admins", method: "POST", body: {}, expectedStatus: 400 }],
      },
    ],
    expectedEntities: ["users", "roles", "audit_logs", "system_config"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "14",
    title: "Master Entity Family",
    featureKey: "master-entity-family",
    moduleGroup: "platform_master",
    routes: ["/company/employees", "/inventory/products", "/services/masters/checklists"],
    primaryRoles: ["admin"],
    fixtureProfile: "master_data",
    wave1Checks: [
      {
        route: "/company/employees",
        entityChecks: [{ table: "employees", minCount: 1 }, { table: "designations", minCount: 1 }, { table: "company_locations", minCount: 1 }],
      },
    ],
    expectedEntities: ["employees", "designations", "company_locations", "products", "suppliers", "services", "daily_checklists"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "5.7",
    title: "Super Admin Runtime Chain",
    featureKey: "super-admin-runtime-chain",
    moduleGroup: "platform_master",
    routes: ["/settings/permissions", "/settings/company", "/settings/audit-logs"],
    primaryRoles: ["super_admin"],
    fixtureProfile: "workflow",
    wave1Checks: [{ route: "/settings/permissions", readyText: "Role & Permissions" }],
    wave2Scenario: {
      scenarioKey: "super_admin_runtime_chain",
      title: "RBAC mutation and system configuration audit trail",
      ownerRoles: ["super_admin"],
      statusTransitions: ["roles.permissions -> updated", "system_config.value -> updated"],
      evidenceTables: ["roles", "system_config", "audit_logs"],
    },
    expectedEntities: ["roles", "system_config", "audit_logs"],
    expectedNotifications: [],
  }),
];
const procurementBillingFeatures: ScopedFeatureTestConfig[] = [
  feature({
    scopeSection: "5.1",
    title: "Buyer Requests",
    featureKey: "buyer-requests",
    moduleGroup: "procurement_billing",
    routes: ["/buyer/requests", "/buyer/requests/new"],
    primaryRoles: ["buyer"],
    fixtureProfile: "procurement_core",
    wave1Checks: [
      {
        route: "/buyer/requests",
        readyText: "My Requests",
        ctaText: "New Order Request",
        entityChecks: [{ table: "requests", minCount: 1 }, { table: "request_items", minCount: 1 }],
      },
    ],
    expectedEntities: ["requests", "request_items"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "5.1",
    title: "Indent Verification",
    featureKey: "inventory-indent-verification",
    moduleGroup: "procurement_billing",
    routes: ["/inventory/indents/verification"],
    primaryRoles: ["admin"],
    fixtureProfile: "procurement_core",
    wave1Checks: [
      {
        route: "/inventory/indents/verification",
        entityChecks: [{ table: "indents", minCount: 1 }, { table: "indent_items", minCount: 1 }],
      },
    ],
    expectedEntities: ["indents", "indent_items"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "5.1",
    title: "Purchase Orders",
    featureKey: "inventory-purchase-orders",
    moduleGroup: "procurement_billing",
    routes: ["/inventory/purchase-orders", "/supplier/purchase-orders"],
    primaryRoles: ["admin"],
    fixtureProfile: "procurement_core",
    wave1Checks: [
      {
        route: "/inventory/purchase-orders",
        readyText: "Purchase Orders",
        ctaText: "Raise New PO",
        entityChecks: [{ table: "purchase_orders", minCount: 1 }, { table: "purchase_order_items", minCount: 1 }],
      },
    ],
    expectedEntities: ["purchase_orders", "purchase_order_items"],
    expectedNotifications: ["po_issued"],
  }),
  feature({
    scopeSection: "5.1",
    title: "Material Receipts",
    featureKey: "inventory-grn",
    moduleGroup: "procurement_billing",
    routes: ["/inventory/grn"],
    primaryRoles: ["storekeeper"],
    fixtureProfile: "procurement_core",
    wave1Checks: [{ route: "/inventory/grn", readyText: "Material Receipts (GRN)" }],
    expectedEntities: ["material_receipts", "material_receipt_items"],
    expectedNotifications: ["shortage_note_raised"],
  }),
  feature({
    scopeSection: "5.1",
    title: "Supplier Bills",
    featureKey: "finance-supplier-bills",
    moduleGroup: "procurement_billing",
    routes: ["/finance/supplier-bills", "/supplier/bills"],
    primaryRoles: ["account"],
    fixtureProfile: "procurement_core",
    wave1Checks: [
      {
        route: "/finance/supplier-bills",
        readyText: "Supplier Payout Registry",
        entityChecks: [{ table: "purchase_bills", minCount: 1 }],
      },
    ],
    expectedEntities: ["purchase_bills", "purchase_bill_items", "payments"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "5.1",
    title: "Buyer Invoices",
    featureKey: "finance-buyer-invoices",
    moduleGroup: "procurement_billing",
    routes: ["/finance/buyer-invoices", "/buyer/invoices"],
    primaryRoles: ["account"],
    fixtureProfile: "procurement_core",
    wave1Checks: [{ route: "/finance/buyer-invoices", entityChecks: [{ table: "sale_bills", minCount: 0 }] }],
    expectedEntities: ["sale_bills", "sale_bill_items", "payments"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "5.1",
    title: "Reconciliation",
    featureKey: "finance-reconciliation",
    moduleGroup: "procurement_billing",
    routes: ["/finance/reconciliation"],
    primaryRoles: ["account"],
    fixtureProfile: "procurement_core",
    wave1Checks: [{ route: "/finance/reconciliation", entityChecks: [{ table: "reconciliations", minCount: 0 }] }],
    expectedEntities: ["reconciliations", "purchase_bills", "purchase_orders", "material_receipts"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "5.1",
    title: "Payments",
    featureKey: "finance-payments",
    moduleGroup: "procurement_billing",
    routes: ["/finance/payments"],
    primaryRoles: ["account"],
    fixtureProfile: "procurement_core",
    wave1Checks: [
      {
        route: "/finance/payments",
        entityChecks: [{ table: "payments", minCount: 0 }, { table: "payment_methods", minCount: 1 }],
      },
    ],
    expectedEntities: ["payments", "payment_methods"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "5.1",
    title: "Return To Vendor",
    featureKey: "tickets-returns",
    moduleGroup: "procurement_billing",
    routes: ["/tickets/returns"],
    primaryRoles: ["storekeeper"],
    fixtureProfile: "procurement_core",
    wave1Checks: [{ route: "/tickets/returns", entityChecks: [{ table: "rtv_tickets", minCount: 1 }] }],
    expectedEntities: ["rtv_tickets"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "13",
    title: "Procurement API Family",
    featureKey: "procurement-api-family",
    moduleGroup: "procurement_billing",
    routes: ["/buyer/requests", "/inventory/purchase-orders", "/finance/reconciliation"],
    primaryRoles: ["admin"],
    fixtureProfile: "procurement_core",
    wave1Checks: [{ route: "/inventory/purchase-orders", readyText: "Purchase Orders" }],
    expectedEntities: ["requests", "indents", "purchase_orders", "material_receipts", "purchase_bills", "reconciliations"],
    expectedNotifications: ["po_issued", "shortage_note_raised"],
  }),
  feature({
    scopeSection: "14",
    title: "Procurement Entity Family",
    featureKey: "procurement-entity-family",
    moduleGroup: "procurement_billing",
    routes: ["/inventory/purchase-orders", "/finance/supplier-bills"],
    primaryRoles: ["account"],
    fixtureProfile: "procurement_core",
    wave1Checks: [
      {
        route: "/finance/supplier-bills",
        entityChecks: [
          { table: "requests", minCount: 1 },
          { table: "indents", minCount: 1 },
          { table: "purchase_orders", minCount: 1 },
          { table: "purchase_bills", minCount: 1 },
        ],
      },
    ],
    expectedEntities: ["requests", "request_items", "indents", "indent_items", "purchase_orders", "purchase_order_items", "material_receipts", "material_receipt_items", "purchase_bills", "sale_bills", "reconciliations", "payments", "rtv_tickets"],
    expectedNotifications: ["po_issued", "shortage_note_raised"],
  }),
  feature({
    scopeSection: "5.1",
    title: "Material Supply Chain",
    featureKey: "procurement-material-supply-chain",
    moduleGroup: "procurement_billing",
    routes: ["/buyer/requests", "/inventory/purchase-orders", "/finance/reconciliation"],
    primaryRoles: ["buyer", "admin", "account"],
    fixtureProfile: "workflow",
    wave1Checks: [{ route: "/buyer/requests", readyText: "My Requests" }],
    wave2Scenario: {
      scenarioKey: "material_supply_chain",
      title: "Buyer request through PO, GRN, billing, payment, reconciliation, and feedback",
      ownerRoles: ["buyer", "admin", "account"],
      statusTransitions: ["requests.pending -> po_issued -> completed", "purchase_orders.sent_to_vendor -> partial_received", "purchase_bills.submitted -> approved", "sale_bills.sent -> acknowledged", "reconciliations.matched"],
      evidenceTables: ["requests", "indents", "purchase_orders", "material_receipts", "purchase_bills", "sale_bills", "payments", "reconciliations", "buyer_feedback", "notifications"],
    },
    expectedEntities: ["requests", "indents", "purchase_orders", "material_receipts", "purchase_bills", "sale_bills", "payments", "reconciliations", "buyer_feedback"],
    expectedNotifications: ["po_issued"],
  }),
];
const societySecurityFeatures: ScopedFeatureTestConfig[] = [
  feature({
    scopeSection: "7.4",
    title: "Guard Station",
    featureKey: "guard-station",
    moduleGroup: "society_security",
    routes: ["/guard"],
    primaryRoles: ["security_guard"],
    fixtureProfile: "society_security",
    wave1Checks: [{ route: "/guard", readyText: "Guard Station", ctaText: "Register New Visitor", secondaryText: "Resident Verification" }],
    expectedEntities: ["visitors", "panic_alerts", "daily_checklists", "residents"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "8.1",
    title: "Visitor Management",
    featureKey: "society-visitors",
    moduleGroup: "society_security",
    routes: ["/society/visitors"],
    primaryRoles: ["society_manager"],
    fixtureProfile: "society_security",
    wave1Checks: [{ route: "/society/visitors", readyText: "Visitor Management", ctaText: "Quick Entry", entityChecks: [{ table: "visitors", minCount: 1 }] }],
    expectedEntities: ["visitors", "residents", "flats", "societies"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "7.4",
    title: "Panic Alerts",
    featureKey: "society-panic-alerts",
    moduleGroup: "society_security",
    routes: ["/society/panic-alerts"],
    primaryRoles: ["society_manager"],
    fixtureProfile: "society_security",
    wave1Checks: [{ route: "/society/panic-alerts", entityChecks: [{ table: "panic_alerts", minCount: 1 }] }],
    expectedEntities: ["panic_alerts", "security_guards", "company_locations"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "7.4",
    title: "Checklist Oversight",
    featureKey: "society-checklists",
    moduleGroup: "society_security",
    routes: ["/society/checklists"],
    primaryRoles: ["society_manager"],
    fixtureProfile: "society_security",
    wave1Checks: [{ route: "/society/checklists", entityChecks: [{ table: "daily_checklists", minCount: 1 }] }],
    expectedEntities: ["daily_checklists", "checklist_responses"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "8.1",
    title: "Emergency Contacts",
    featureKey: "society-emergency",
    moduleGroup: "society_security",
    routes: ["/society/emergency"],
    primaryRoles: ["society_manager"],
    fixtureProfile: "society_security",
    wave1Checks: [{ route: "/society/emergency", entityChecks: [{ table: "emergency_contacts", minCount: 1 }] }],
    expectedEntities: ["emergency_contacts"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "8.1",
    title: "Resident Directory",
    featureKey: "society-residents",
    moduleGroup: "society_security",
    routes: ["/society/residents"],
    primaryRoles: ["society_manager"],
    fixtureProfile: "society_security",
    wave1Checks: [{ route: "/society/residents", entityChecks: [{ table: "residents", minCount: 1 }] }],
    expectedEntities: ["residents", "flats", "societies"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "8.1",
    title: "Resident Portal",
    featureKey: "resident-portal",
    moduleGroup: "society_security",
    routes: ["/resident"],
    primaryRoles: ["resident"],
    fixtureProfile: "society_security",
    wave1Checks: [{ route: "/resident", secondaryText: "Manage your flat and visitor access" }],
    expectedEntities: ["residents", "visitors", "notifications"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "8.2",
    title: "Quality Tickets",
    featureKey: "tickets-quality",
    moduleGroup: "society_security",
    routes: ["/tickets/quality"],
    primaryRoles: ["storekeeper"],
    fixtureProfile: "society_security",
    wave1Checks: [{ route: "/tickets/quality", entityChecks: [{ table: "rtv_tickets", minCount: 1 }] }],
    expectedEntities: ["material_receipts", "shortage_notes", "audit_logs"],
    expectedNotifications: ["shortage_note_raised"],
  }),
  feature({
    scopeSection: "8.2",
    title: "Behavior Tickets",
    featureKey: "tickets-behavior",
    moduleGroup: "society_security",
    routes: ["/tickets/behavior"],
    primaryRoles: ["site_supervisor"],
    fixtureProfile: "society_security",
    wave1Checks: [{ route: "/tickets/behavior", entityChecks: [{ table: "employee_behavior_tickets", minCount: 0 }] }],
    expectedEntities: ["employee_behavior_tickets", "employees"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "11.10",
    title: "Society Manager Dashboard",
    featureKey: "society-dashboard-manager",
    moduleGroup: "society_security",
    routes: ["/dashboard"],
    primaryRoles: ["society_manager"],
    fixtureProfile: "society_security",
    wave1Checks: [{ route: "/dashboard" }],
    expectedEntities: ["visitors", "panic_alerts", "checklist_responses"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "11.9",
    title: "Security Supervisor Dashboard",
    featureKey: "society-dashboard-supervisor",
    moduleGroup: "society_security",
    routes: ["/dashboard"],
    primaryRoles: ["security_supervisor"],
    fixtureProfile: "society_security",
    wave1Checks: [{ route: "/dashboard" }],
    expectedEntities: ["attendance_logs", "panic_alerts", "visitors"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "14",
    title: "Society & Security Entity Family",
    featureKey: "society-security-entity-family",
    moduleGroup: "society_security",
    routes: ["/guard", "/society/visitors", "/tickets/behavior"],
    primaryRoles: ["society_manager"],
    fixtureProfile: "society_security",
    wave1Checks: [
      {
        route: "/society/visitors",
        entityChecks: [{ table: "visitors", minCount: 1 }, { table: "residents", minCount: 1 }, { table: "emergency_contacts", minCount: 1 }, { table: "panic_alerts", minCount: 1 }],
      },
    ],
    expectedEntities: ["visitors", "residents", "flats", "societies", "emergency_contacts", "panic_alerts", "daily_checklists", "checklist_responses", "employee_behavior_tickets"],
    expectedNotifications: ["shortage_note_raised"],
  }),
  feature({
    scopeSection: "5.4",
    title: "Visitor & Society Chain",
    featureKey: "visitor-society-chain",
    moduleGroup: "society_security",
    routes: ["/guard", "/resident", "/society/visitors"],
    primaryRoles: ["security_guard", "resident", "society_manager"],
    fixtureProfile: "workflow",
    wave1Checks: [{ route: "/guard", readyText: "Guard Station" }],
    wave2Scenario: {
      scenarioKey: "visitor_society_chain",
      title: "Guard log to resident approval and society visibility",
      ownerRoles: ["security_guard", "resident", "society_manager"],
      statusTransitions: ["visitors.approved_by_resident: null -> true", "visitor_pass_number assigned"],
      evidenceTables: ["visitors", "audit_logs"],
    },
    expectedEntities: ["visitors", "residents", "flats", "societies"],
    expectedNotifications: [],
  }),
];

const hrmsServiceFeatures: ScopedFeatureTestConfig[] = [
  feature({
    scopeSection: "9.2",
    title: "Attendance",
    featureKey: "hrms-attendance",
    moduleGroup: "hrms_service",
    routes: ["/hrms/attendance"],
    primaryRoles: ["security_supervisor"],
    fixtureProfile: "hrms_core",
    wave1Checks: [{ route: "/hrms/attendance", readyText: "Smart Attendance", entityChecks: [{ table: "attendance_logs", minCount: 1 }] }],
    expectedEntities: ["attendance_logs", "employee_shift_assignments", "company_locations"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "9.2",
    title: "Leave Management",
    featureKey: "hrms-leave",
    moduleGroup: "hrms_service",
    routes: ["/hrms/leave"],
    primaryRoles: ["admin"],
    fixtureProfile: "hrms_core",
    wave1Checks: [{ route: "/hrms/leave", readyText: "Leave Management", entityChecks: [{ table: "leave_applications", minCount: 1 }] }],
    expectedEntities: ["leave_applications", "leave_types", "notifications"],
    expectedNotifications: ["leave_status_update"],
  }),
  feature({
    scopeSection: "9.2",
    title: "Payroll",
    featureKey: "hrms-payroll",
    moduleGroup: "hrms_service",
    routes: ["/hrms/payroll"],
    primaryRoles: ["account"],
    fixtureProfile: "hrms_core",
    wave1Checks: [{ route: "/hrms/payroll", readyText: "Personnel Payroll", ctaText: "Create Payroll Cycle", entityChecks: [{ table: "payroll_cycles", minCount: 1 }] }],
    expectedEntities: ["payroll_cycles", "payslips", "attendance_logs"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "9.2",
    title: "Recruitment",
    featureKey: "hrms-recruitment",
    moduleGroup: "hrms_service",
    routes: ["/hrms/recruitment"],
    primaryRoles: ["admin"],
    fixtureProfile: "hrms_core",
    wave1Checks: [{ route: "/hrms/recruitment", readyText: "Recruitment Portal", ctaText: "Add New Candidate", entityChecks: [{ table: "candidates", minCount: 1 }] }],
    expectedEntities: ["candidates", "background_verifications", "employees"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "9.2",
    title: "HR Incidents",
    featureKey: "hrms-incidents",
    moduleGroup: "hrms_service",
    routes: ["/hrms/incidents"],
    primaryRoles: ["admin"],
    fixtureProfile: "hrms_core",
    wave1Checks: [{ route: "/hrms/incidents", readyText: "HR Incidents", entityChecks: [{ table: "employee_behavior_tickets", minCount: 0 }] }],
    expectedEntities: ["employee_behavior_tickets"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "10.1",
    title: "Service Requests",
    featureKey: "service-requests-list",
    moduleGroup: "hrms_service",
    routes: ["/service-requests"],
    primaryRoles: ["site_supervisor"],
    fixtureProfile: "service_ops",
    wave1Checks: [{ route: "/service-requests", readyText: "Service Requests", ctaText: "New Request", entityChecks: [{ table: "service_requests", minCount: 1 }] }],
    expectedEntities: ["service_requests"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "10.1",
    title: "Service Request Board",
    featureKey: "service-requests-board",
    moduleGroup: "hrms_service",
    routes: ["/service-requests/board"],
    primaryRoles: ["site_supervisor"],
    fixtureProfile: "service_ops",
    wave1Checks: [{ route: "/service-requests/board", secondaryText: "In Progress", entityChecks: [{ table: "service_requests", minCount: 1 }] }],
    expectedEntities: ["service_requests"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "10.1",
    title: "Create Service Request",
    featureKey: "service-requests-create",
    moduleGroup: "hrms_service",
    routes: ["/service-requests/new"],
    primaryRoles: ["site_supervisor"],
    fixtureProfile: "service_ops",
    wave1Checks: [{ route: "/service-requests/new", readyText: "Create Service Request", ctaText: "Create Request" }],
    expectedEntities: ["service_requests", "services", "company_locations", "societies"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "10.2",
    title: "AC Operations",
    featureKey: "services-ac",
    moduleGroup: "hrms_service",
    routes: ["/services/ac"],
    primaryRoles: ["ac_technician"],
    fixtureProfile: "service_ops",
    wave1Checks: [{ route: "/services/ac", readyText: "Air Conditioner Services" }],
    expectedEntities: ["service_requests", "services", "technician_profiles"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "10.2",
    title: "Pest Operations",
    featureKey: "services-pest-control",
    moduleGroup: "hrms_service",
    routes: ["/services/pest-control"],
    primaryRoles: ["pest_control_technician"],
    fixtureProfile: "service_ops",
    wave1Checks: [{ route: "/services/pest-control", readyText: "Pest Control Services" }],
    expectedEntities: ["service_requests", "services", "pest_control_ppe_verifications"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "10.2",
    title: "Service Boy Portal",
    featureKey: "service-boy-portal",
    moduleGroup: "hrms_service",
    routes: ["/service-boy"],
    primaryRoles: ["service_boy"],
    fixtureProfile: "service_ops",
    wave1Checks: [{ route: "/service-boy", readyText: "Technician Portal" }],
    expectedEntities: ["service_requests", "job_sessions"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "11.13",
    title: "Site Supervisor Dashboard",
    featureKey: "site-supervisor-dashboard",
    moduleGroup: "hrms_service",
    routes: ["/dashboard"],
    primaryRoles: ["site_supervisor"],
    fixtureProfile: "service_ops",
    wave1Checks: [{ route: "/dashboard" }],
    expectedEntities: ["service_requests", "attendance_logs"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "11.14",
    title: "Service Boy Dashboard",
    featureKey: "service-boy-dashboard",
    moduleGroup: "hrms_service",
    routes: ["/dashboard"],
    primaryRoles: ["service_boy"],
    fixtureProfile: "service_ops",
    wave1Checks: [{ route: "/dashboard" }],
    expectedEntities: ["service_requests", "job_sessions"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "11.16",
    title: "AC Technician Dashboard",
    featureKey: "ac-technician-dashboard",
    moduleGroup: "hrms_service",
    routes: ["/dashboard"],
    primaryRoles: ["ac_technician"],
    fixtureProfile: "service_ops",
    wave1Checks: [{ route: "/dashboard" }],
    expectedEntities: ["service_requests", "job_sessions"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "11.17",
    title: "Pest Technician Dashboard",
    featureKey: "pest-technician-dashboard",
    moduleGroup: "hrms_service",
    routes: ["/dashboard"],
    primaryRoles: ["pest_control_technician"],
    fixtureProfile: "service_ops",
    wave1Checks: [{ route: "/dashboard" }],
    expectedEntities: ["service_requests", "job_sessions"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "13",
    title: "HRMS & Service API Family",
    featureKey: "hrms-service-api-family",
    moduleGroup: "hrms_service",
    routes: ["/hrms/attendance", "/service-requests", "/services/ac"],
    primaryRoles: ["admin"],
    fixtureProfile: "hrms_core",
    wave1Checks: [{ route: "/service-requests", readyText: "Service Requests" }],
    expectedEntities: ["attendance_logs", "leave_applications", "payroll_cycles", "service_requests", "job_sessions"],
    expectedNotifications: ["leave_status_update"],
  }),
  feature({
    scopeSection: "14",
    title: "HRMS & Service Entity Family",
    featureKey: "hrms-service-entity-family",
    moduleGroup: "hrms_service",
    routes: ["/hrms/payroll", "/service-requests"],
    primaryRoles: ["admin"],
    fixtureProfile: "hrms_core",
    wave1Checks: [{ route: "/hrms/payroll", entityChecks: [{ table: "attendance_logs", minCount: 1 }, { table: "leave_applications", minCount: 1 }, { table: "service_requests", minCount: 1 }] }],
    expectedEntities: ["attendance_logs", "leave_applications", "payroll_cycles", "payslips", "candidates", "background_verifications", "service_requests", "job_sessions", "job_photos", "job_materials_used"],
    expectedNotifications: ["leave_status_update"],
  }),
  feature({
    scopeSection: "5.5",
    title: "HRMS Attendance, Leave & Payroll Chain",
    featureKey: "hrms-attendance-leave-payroll-chain",
    moduleGroup: "hrms_service",
    routes: ["/hrms/leave", "/hrms/payroll"],
    primaryRoles: ["admin", "account"],
    fixtureProfile: "workflow",
    wave1Checks: [{ route: "/hrms/leave", readyText: "Leave Management" }],
    wave2Scenario: {
      scenarioKey: "hrms_attendance_leave_payroll_chain",
      title: "Attendance evidence to leave approval and payroll visibility",
      ownerRoles: ["security_supervisor", "admin", "account"],
      statusTransitions: ["attendance_logs.present", "leave_applications.pending -> approved", "payroll_cycles.draft -> approved"],
      evidenceTables: ["attendance_logs", "leave_applications", "notifications", "payroll_cycles", "payslips"],
    },
    expectedEntities: ["attendance_logs", "leave_applications", "notifications", "payroll_cycles", "payslips"],
    expectedNotifications: ["leave_status_update"],
  }),
  feature({
    scopeSection: "5.6",
    title: "AC Job Execution Chain",
    featureKey: "ac-job-execution-chain",
    moduleGroup: "hrms_service",
    routes: ["/service-requests/new", "/services/ac"],
    primaryRoles: ["site_supervisor", "ac_technician"],
    fixtureProfile: "workflow",
    wave1Checks: [{ route: "/service-requests/new", readyText: "Create Service Request" }],
    wave2Scenario: {
      scenarioKey: "ac_job_execution_chain",
      title: "Request creation, assignment, before/after evidence, and completion",
      ownerRoles: ["site_supervisor", "ac_technician"],
      statusTransitions: ["service_requests.open -> assigned -> in_progress -> completed"],
      evidenceTables: ["service_requests", "job_sessions", "job_photos"],
    },
    expectedEntities: ["service_requests", "job_sessions", "job_photos"],
    expectedNotifications: [],
  }),
  feature({
    scopeSection: "5.2",
    title: "Service Deployment Chain",
    featureKey: "service-deployment-chain",
    moduleGroup: "hrms_service",
    routes: ["/dashboard", "/service-requests"],
    primaryRoles: ["site_supervisor", "company_hod"],
    fixtureProfile: "workflow",
    wave1Checks: [{ route: "/dashboard" }],
    wave2Scenario: {
      scenarioKey: "service_deployment_chain",
      title: "Vendor matching, service PO, dispatch, acknowledgment, and billing",
      ownerRoles: ["company_hod", "site_supervisor"],
      statusTransitions: ["service_purchase_orders.issued", "service_acknowledgments.created"],
      evidenceTables: ["service_purchase_orders", "personnel_dispatches", "service_delivery_notes", "service_acknowledgments"],
    },
    expectedEntities: ["service_purchase_orders", "personnel_dispatches", "service_delivery_notes", "service_acknowledgments"],
    expectedNotifications: [],
    deferredReason: "Current app surface has hooks for dispatch and delivery-note entities but no complete UI path for end-to-end supervisor acknowledgment and billing verification.",
  }),
  feature({
    scopeSection: "5.6",
    title: "Pest Job Chain",
    featureKey: "pest-job-chain",
    moduleGroup: "hrms_service",
    routes: ["/services/pest-control"],
    primaryRoles: ["pest_control_technician"],
    fixtureProfile: "workflow",
    wave1Checks: [{ route: "/services/pest-control", readyText: "Pest Control Services" }],
    wave2Scenario: {
      scenarioKey: "pest_job_chain",
      title: "PPE verification, chemical logging, and closure",
      ownerRoles: ["pest_control_technician", "site_supervisor"],
      statusTransitions: ["service_requests.open -> in_progress -> completed"],
      evidenceTables: ["service_requests", "job_sessions", "job_materials_used", "pest_control_ppe_verifications"],
    },
    expectedEntities: ["service_requests", "job_sessions", "job_materials_used", "pest_control_ppe_verifications"],
    expectedNotifications: [],
    deferredReason: "Pest PPE verification is not reliably request-scoped in the current implementation, so a deterministic end-to-end technician flow is blocked until the product bug is fixed.",
  }),
];

export const scopedFeatureMatrix: ScopedFeatureTestConfig[] = [
  ...platformMasterFeatures,
  ...procurementBillingFeatures,
  ...societySecurityFeatures,
  ...hrmsServiceFeatures,
];

export function getFeaturesForModule(moduleGroup: FeatureModuleGroup) {
  return scopedFeatureMatrix.filter((featureConfig) => featureConfig.moduleGroup === moduleGroup);
}
