import { buildPayslipPdfLayout, type PayrollPayslipRow } from "@/src/lib/payroll/payrollTransforms";

type AutoTableDoc = {
  autoTable: (...args: unknown[]) => void;
  lastAutoTable?: {
    finalY: number;
  };
};

export async function downloadPayslipPdf(
  payslip: PayrollPayslipRow,
  formatCurrency: (amount: number) => string,
): Promise<{ success: boolean; error?: unknown }> {
  try {
    const { default: jsPDF } = await import("jspdf");
    const doc = new jsPDF();
    const pdfDoc = doc as InstanceType<typeof jsPDF> & AutoTableDoc;
    const layout = buildPayslipPdfLayout(payslip);

    doc.setFontSize(18);
    doc.text("PAYSLIP", 105, 15, { align: "center" });

    doc.setFontSize(10);
    doc.text(`Payslip #: ${payslip.payslip_number}`, 14, 25);
    doc.text(`Period: ${layout.periodLabel}`, 14, 30);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 35);

    pdfDoc.autoTable({
      startY: layout.defaultFinalY,
      head: layout.header,
      body: layout.employeeRows,
      theme: "grid",
      headStyles: { fillColor: [41, 128, 185] },
      styles: { fontSize: 10, cellPadding: 3 },
    });

    pdfDoc.autoTable({
      startY: (pdfDoc.lastAutoTable?.finalY ?? layout.defaultFinalY) + 10,
      head: [["Earnings", "Amount", "Deductions", "Amount"]],
      body: layout.earningsRows.map(([earnLabel, earnAmount, deductLabel, deductAmount]) => [
        earnLabel,
        formatCurrency(Number(earnAmount)),
        deductLabel,
        formatCurrency(Number(deductAmount)),
      ]),
      theme: "striped",
      headStyles: { fillColor: [52, 73, 94] },
      foot: [["", "", layout.footerLabel, formatCurrency(layout.netPayable)]],
      footStyles: { fillColor: [46, 204, 113], fontStyle: "bold" },
    });

    const finalY = (pdfDoc.lastAutoTable?.finalY ?? layout.defaultFinalY) + 20;
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text("This is valid proof of income generated by the Organization's Operational Truth Engine.", 14, finalY);

    doc.save(`Payslip_${payslip.payslip_number}.pdf`);

    return { success: true };
  } catch (error: unknown) {
    return { success: false, error };
  }
}
