"use client";

import { useState, useEffect, useCallback } from "react";
import { supabase } from "@/src/lib/supabaseClient";
import type {
  Asset,
  AssetInsert,
  AssetUpdate,
  AssetWithDetails,
  AssetFilters,
  AssetDashboardStats,
} from "@/src/types/operations";
import { PAGINATION } from "@/src/lib/constants";
import { sanitizeLikeInput } from "@/lib/sanitize";

interface UseAssetsState {
  assets: AssetWithDetails[];
  totalCount: number;
  currentPage: number;
  pageSize: number;
  isLoading: boolean;
  error: string | null;
  stats: AssetDashboardStats | null;
}

interface UseAssetsReturn extends UseAssetsState {
  createAsset: (data: AssetInsert) => Promise<{ success: boolean; error?: string; data?: Asset }>;
  updateAsset: (id: string, data: AssetUpdate) => Promise<{ success: boolean; error?: string }>;
  deleteAsset: (id: string) => Promise<{ success: boolean; error?: string }>;
  getAssetById: (id: string) => Promise<AssetWithDetails | null>;
  setFilters: (filters: AssetFilters) => void;
  setPage: (page: number) => void;
  setPageSize: (size: number) => void;
  refresh: () => void;
  fetchStats: () => Promise<void>;
}

/**
 * Hook for managing assets with filtering, pagination, and statistics
 */
export function useAssets(initialFilters?: AssetFilters): UseAssetsReturn {
  const [state, setState] = useState<UseAssetsState>({
    assets: [],
    totalCount: 0,
    currentPage: 1,
    pageSize: PAGINATION.DEFAULT_PAGE_SIZE,
    isLoading: true,
    error: null,
    stats: null,
  });

  const [filters, setFiltersState] = useState<AssetFilters>(initialFilters || {});

  // Fetch assets with filters and pagination
  const fetchAssets = useCallback(async () => {
    try {
      setState((prev) => ({ ...prev, isLoading: true, error: null }));

      let query = supabase
        .from("assets_with_details")
        .select("*", { count: "exact" });

      // Apply filters
      if (filters.categoryId) {
        query = query.eq("category_id", filters.categoryId);
      }
      if (filters.locationId) {
        query = query.eq("location_id", filters.locationId);
      }
      if (filters.societyId) {
        query = query.eq("society_id", filters.societyId);
      }
      if (filters.status) {
        query = query.eq("status", filters.status);
      }
      if (filters.searchTerm) {
        query = query.or(
          `name.ilike.%${sanitizeLikeInput(filters.searchTerm)}%,asset_code.ilike.%${sanitizeLikeInput(filters.searchTerm)}%,description.ilike.%${sanitizeLikeInput(filters.searchTerm)}%`
        );
      }

      // Pagination
      const from = (state.currentPage - 1) * state.pageSize;
      const to = from + state.pageSize - 1;

      const { data, error, count } = await query
        .order("created_at", { ascending: false })
        .range(from, to);

      if (error) throw error;

      setState((prev) => ({
        ...prev,
        assets: (data as AssetWithDetails[]) || [],
        totalCount: count || 0,
        isLoading: false,
        error: null,
      }));
    } catch (err: unknown) {
      const errorMessage = err instanceof Error ? err.message : "Failed to fetch assets";
      console.error("Error fetching assets:", err);
      setState((prev) => ({
        ...prev,
        isLoading: false,
        error: errorMessage,
      }));
    }
  }, [filters, state.currentPage, state.pageSize]);

  // Fetch dashboard statistics
  const fetchStats = useCallback(async () => {
    try {
      // Get counts by status
      const { data: statusCounts, error: statusError } = await supabase
        .from("assets")
        .select("status")
        .not("status", "is", null);

      if (statusError) throw statusError;

      // Get upcoming maintenance count
      const { count: upcomingMaintenance, error: maintenanceError } = await supabase
        .from("due_maintenance_schedules")
        .select("*", { count: "exact", head: true });

      if (maintenanceError) throw maintenanceError;

      // Calculate stats
      const stats: AssetDashboardStats = {
        totalAssets: statusCounts?.length || 0,
        functionalAssets: statusCounts?.filter((a) => a.status === "functional").length || 0,
        underMaintenance: statusCounts?.filter((a) => a.status === "under_maintenance").length || 0,
        faultyAssets: statusCounts?.filter((a) => a.status === "faulty").length || 0,
        decommissioned: statusCounts?.filter((a) => a.status === "decommissioned").length || 0,
        upcomingMaintenance: upcomingMaintenance || 0,
      };

      setState((prev) => ({ ...prev, stats }));
    } catch (err: unknown) {
      console.error("Error fetching asset stats:", err);
    }
  }, []);

  // Create new asset (asset_code is auto-generated by trigger)
  const createAsset = useCallback(
    async (data: AssetInsert): Promise<{ success: boolean; error?: string; data?: Asset }> => {
      try {
        const insertData = { ...data } as AssetInsert & { asset_code?: string | null };

        // Let the database trigger generate the code when the caller did not provide one.
        if (!insertData.asset_code) {
          delete insertData.asset_code;
        }

        const { data: newAsset, error } = await supabase
          .from("assets")
          .insert(insertData)
          .select()
          .single();

        if (error) throw error;

        // Refresh the list to show the new asset with generated code
        fetchAssets();

        return { success: true, data: newAsset };
      } catch (err: unknown) {
        const errorMessage = err instanceof Error ? err.message : "Failed to create asset";
        console.error("Error creating asset:", err);
        return { success: false, error: errorMessage };
      }
    },
    [fetchAssets]
  );

  // Update asset
  const updateAsset = useCallback(
    async (id: string, data: AssetUpdate): Promise<{ success: boolean; error?: string }> => {
      try {
        const { error } = await supabase.from("assets").update(data).eq("id", id);

        if (error) throw error;

        // Refresh to get updated view data
        fetchAssets();

        return { success: true };
      } catch (err: unknown) {
        const errorMessage = err instanceof Error ? err.message : "Failed to update asset";
        console.error("Error updating asset:", err);
        return { success: false, error: errorMessage };
      }
    },
    [fetchAssets]
  );

  // Delete asset (soft delete by setting status to decommissioned)
  const deleteAsset = useCallback(
    async (id: string): Promise<{ success: boolean; error?: string }> => {
      try {
        const { error } = await supabase
          .from("assets")
          .update({ status: "decommissioned" })
          .eq("id", id);

        if (error) throw error;

        fetchAssets();

        return { success: true };
      } catch (err: unknown) {
        const errorMessage = err instanceof Error ? err.message : "Failed to delete asset";
        console.error("Error deleting asset:", err);
        return { success: false, error: errorMessage };
      }
    },
    [fetchAssets]
  );

  // Get single asset by ID
  const getAssetById = useCallback(
    async (id: string): Promise<AssetWithDetails | null> => {
      try {
        const { data, error } = await supabase
          .from("assets_with_details")
          .select("*")
          .eq("id", id)
          .single();

        if (error) throw error;

        return data as AssetWithDetails;
      } catch (err: unknown) {
        console.error("Error fetching asset by ID:", err);
        return null;
      }
    },
    []
  );

  // Set filters (resets to page 1)
  const setFilters = useCallback((newFilters: AssetFilters) => {
    setFiltersState(newFilters);
    setState((prev) => ({ ...prev, currentPage: 1 }));
  }, []);

  // Set current page
  const setPage = useCallback((page: number) => {
    setState((prev) => ({ ...prev, currentPage: page }));
  }, []);

  // Set page size
  const setPageSize = useCallback((size: number) => {
    setState((prev) => ({ ...prev, pageSize: size, currentPage: 1 }));
  }, []);

  // Refresh data
  const refresh = useCallback(() => {
    fetchAssets();
    fetchStats();
  }, [fetchAssets, fetchStats]);

  // Fetch on mount and when dependencies change
  useEffect(() => {
    fetchAssets();
  }, [fetchAssets]);

  // Fetch stats on mount
  useEffect(() => {
    fetchStats();
  }, [fetchStats]);

  return {
    ...state,
    createAsset,
    updateAsset,
    deleteAsset,
    getAssetById,
    setFilters,
    setPage,
    setPageSize,
    refresh,
    fetchStats,
  };
}
